# Site settings
title: "Kit Pearson | Resume"

# Build settings

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:         "true"
resume_name:           "Kit Pearson"
resume_title:          "Web Developer"
resume_contact_email:  "kitpearson@me.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Resume social links
resume_social_links:
  resume_github_url:      "https://github.com/kpearson"
  resume_twitter_url:     "http://twitter.com/kit_pearson"
# resume_facebook_url:  "insert Facebook URL here"
  resume_linkedin_url:    "https://www.linkedin.com/in/kit-pearson-2228977"
  resume_website_url:     "http://trialanderror.io"

# Design settings
resume_theme:                   default

